Sometime the app crash profile view controller when logging out and password reminder is shown
"MEGASdkManager.sharedMEGASdk().myUser" can be nil if the app receives a request finished after the request logout is finished
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value